### ISSUE TITLE
Pick another name

### ISSUE THREAD

**Issue by guaka** [digitalnomads/digitalnomads.github.io#4]
I like the idea of this project and it's great it's done in an open source way. But there's already a project with the name Nomadwiki.

http://nomadwiki.org is not the most active of wikis but there is [regular activity](http://nomadwiki.org/w/index.php?title=Special:RecentChanges&days=30&from=).

It's very confusing you chose nomadwiki.net to host this project. It's not a wiki and it's not Nomadwiki.

Please pick another name and domainname for your project.

**Comment by skatkov** [comment]
Thanks, you might be right on that. I'm mostly focusing on digitalnomad's and nomadwiki might be misleading and also there is your project.

I will consider my options and get back to you on this.

**Comment by guaka** [comment]
Cool!
Happy to promote it prominently on nomadwiki.org (and elsewhere) once you have decided on a good name :)

Why not stick with digitalnomads.github.io for now? and just redirect nomadwiki.net there.

**Comment by simison** [comment]
There are a lot of curated lists like this with `awesome-*` prefix. Would this be cool; `awesome-nomads` or `awesome-digital-nomads`? Remember that if you want to reach people Googling with a term "digital nomads", it's good to have that at the domain as well.

Here's [a big list of these lists](https://github.com/sindresorhus/awesome). Some examples:
- [awesome-ruby](https://github.com/markets/awesome-ruby)
- [awesome-geek-podcasts](https://github.com/cv/awesome-geek-podcasts)
- [awesome-shell](https://github.com/alebcay/awesome-shell)
- [awesome-slack](https://github.com/filipelinhares/awesome-slack)

...and so on.

**Comment by skatkov** [comment]
Thanks for great ideas, keep dropping them.

Also you guys have pretty neat projects and interesting team. I've never heard about you guys, but will be looking into that your doing then I have time :)

I don't think that my general idea about this project is aligned with awesome-\* collections out there. I don't collect links to all the digital nomads stuff/services. I try to show all options people have (or good comparison) so people could make educated choice. 

And 3rd level domain... well it doesn't rate as a serious thing in my brain and i think same pattern applies in others people brain too.

**Comment by simison** [comment]
@skatkov I've understood that the idea of awesome-\* stuff is to have compact, curated lists of awesome resources, not just everything out there on topic. In that way it's aligned with what you're doing. (And many digital nomads are already familiar with the concept via GitHub.)

And thanks. :-) We've got bunch of projects actually and they sort bundle together. I'm listing them all [at my page](http://www.mikaelkorpela.fi/volunteering/).

**Comment by skatkov** [comment]
OK guys, i've bought http://howtodigitalnomad.com , not as cool as nomadwiki.com :P but will do for me. 

I'll make a switch on weekends. 

PS. Sorry this happened, but it's good it happened sooner, then later :)

**Comment by simison** [comment]
No worries man! :-) I think "howto" is a good term for SEO! (As questions often are.)

Could we do a domain transfer in near future? I'd be happy to leave it pointing to your site with `301` code for, say a year, since you've already spread the link around for quite a while.

**Comment by skatkov** [comment]
Good news everyone (c)
I moved to new domain name, redirected the old one, corrected some social 'integrations'. But I didn't managed to redo the logo still (I suck at graphics), huh... 

But soon... soon

**Comment by simison** [comment]
:+1: :+1: thanks

**Comment by skatkov** [comment]
Okey, logo changed. I think this issue is fully resolved now.
